### ISSUE TITLE
BUG! Publishing retry mechanism does not handle 207 response codes correctly

### ISSUE THREAD

**Issue by lightbreeze** [zalando-nakadi/kanadi#153] opened 2020-08-14 14:28 UTC
I discovered that 207 response codes are not handled correctly by Kanadi. The successful events are retried instead of the failed ones.

Tests run on version : 0.7.1

I tried to publish 4 events in a single request, with eids: 
```
9bb77ac1-382b-46e3-a3d1-0c4e2ade8071
173463fc-f323-402a-a364-69357a12d43f
26bb6d0b-d9bd-4ade-9ed2-4f8ff1eb9d86
5539be2c-b9f5-471b-927c-c68c8fcb4db7
```

**TEST 1**
---------------------------------------------------------------------------------------------

I mocked the nakadi endpoint using a local tool, called Mockoon, with following responses:
1. [500 - Internal Server Error] : default response
2. [207 - Multi-Status] : when the request contains 4 items

When calling the `Events.publish` function, the following requests are generated:

1) POST /event-types/fake_shipment_shipped/events
with body:
```
[
    {"metadata":{"eid":"9bb77ac1-382b-46e3-a3d1-0c4e2ade8071","occurred_at":"2020-08-14T14:46:41.257+02:00","event_type":"fake_shipment_shipped"}, ...}]},
    {"metadata":{"eid":"173463fc-f323-402a-a364-69357a12d43f","occurred_at":"2020-08-14T14:46:41.259+02:00","event_type":"fake_shipment_shipped"}, ...}]},
    {"metadata":{"eid":"26bb6d0b-d9bd-4ade-9ed2-4f8ff1eb9d86","occurred_at":"2020-08-14T14:46:41.26+02:00","event_type":"fake_shipment_shipped"}, ...}]},
    {"metadata":{"eid":"5539be2c-b9f5-471b-927c-c68c8fcb4db7","occurred_at":"2020-08-14T14:46:41.261+02:00","event_type":"fake_shipment_shipped"}, ...}]}
]
```
Response: 207
body:
```
[
    {"eid":"173463fc-f323-402a-a364-69357a12d43f","publishing_status":"submitted"},
    {"eid":"26bb6d0b-d9bd-4ade-9ed2-4f8ff1eb9d86","publishing_status":"failed","step":"publishing"},
    {"eid":"5539be2c-b9f5-471b-927c-c68c8fcb4db7","publishing_status":"failed","step":"publishing"},
    {"eid":"9bb77ac1-382b-46e3-a3d1-0c4e2ade8071","publishing_status":"failed","step":"publishing"}
]
```

2) POST /event-types/fake_shipment_shipped/events (repeated 3 times)
with body:
```
[
    {"metadata":{"eid":"173463fc-f323-402a-a364-69357a12d43f","occurred_at":"2020-08-14T14:46:41.259+02:00","event_type":"fake_shipment_shipped"}, ...}]}
]
```
Response: 500
empty body

Result: the second request is retried for 3 times and then the `publish` function returns a Future.Failed
 
Logs from Kanadi:
```
[info] 2020-08-14 14:46:41,854 WARN  org.zalando.kanadi.api.Events - Events with eid's 26bb6d0b-d9bd-4ade-9ed2-4f8ff1eb9d86,5539be2c-b9f5-471b-927c-c68c8fcb4db7,9bb77ac1-382b-46e3-a3d1-0c4e2ade8071 failed to submit, retrying in 15000 millis
[info] 2020-08-14 14:46:56,901 WARN  org.zalando.kanadi.api.Events - Events with eid's 173463fc-f323-402a-a364-69357a12d43f failed to submit, retrying in 15000 millis
[info] 2020-08-14 14:47:11,943 WARN  org.zalando.kanadi.api.Events - Events with eid's 173463fc-f323-402a-a364-69357a12d43f failed to submit, retrying in 15000 millis
[info] 2020-08-14 14:47:26,984 ERROR org.zalando.kanadi.api.Events - Max retry failed for publishing events, event id's still not submitted are 173463fc-f323-402a-a364-69357a12d43f
```

**TEST 2**
---------------------------------------------------------------------------------------------

I mocked the nakadi endpoint using the same tool with following responses:
1. [500 - Internal Server Error] : default response
2. [207 - Multi-Status] : when the request contains 4 items
3. [200 - Ok] : when the request contains 1 element, specifically eid `173463fc-f323-402a-a364-69357a12d43f`

When calling the `Events.publish` function, the following requests are performed:

1) POST /event-types/fake_shipment_shipped/events
with body:
```
[
    {"metadata":{"eid":"9bb77ac1-382b-46e3-a3d1-0c4e2ade8071","occurred_at":"2020-08-14T14:46:41.257+02:00","event_type":"fake_shipment_shipped"}, ...}]},
    {"metadata":{"eid":"173463fc-f323-402a-a364-69357a12d43f","occurred_at":"2020-08-14T14:46:41.259+02:00","event_type":"fake_shipment_shipped"}, ...}]},
    {"metadata":{"eid":"26bb6d0b-d9bd-4ade-9ed2-4f8ff1eb9d86","occurred_at":"2020-08-14T14:46:41.26+02:00","event_type":"fake_shipment_shipped"}, ...}]},
    {"metadata":{"eid":"5539be2c-b9f5-471b-927c-c68c8fcb4db7","occurred_at":"2020-08-14T14:46:41.261+02:00","event_type":"fake_shipment_shipped"}, ...}]}
]
```
Response: 207
body:
```
[
    {"eid":"173463fc-f323-402a-a364-69357a12d43f","publishing_status":"submitted"},
    {"eid":"26bb6d0b-d9bd-4ade-9ed2-4f8ff1eb9d86","publishing_status":"failed","step":"publishing"},
    {"eid":"5539be2c-b9f5-471b-927c-c68c8fcb4db7","publishing_status":"failed","step":"publishing"},
    {"eid":"9bb77ac1-382b-46e3-a3d1-0c4e2ade8071","publishing_status":"failed","step":"publishing"}
]
```

2) POST /event-types/fake_shipment_shipped/events
with body:
```
[
    {"metadata":{"eid":"173463fc-f323-402a-a364-69357a12d43f","occurred_at":"2020-08-14T14:46:41.259+02:00","event_type":"fake_shipment_shipped"}, ...}]}
]
```
Response: 200
empty body

Result: the `publish` function returns a Future.Successful

Logs from Kanadi:
```
[info] 2020-08-14 14:46:41,854 WARN  org.zalando.kanadi.api.Events - Events with eid's 26bb6d0b-d9bd-4ade-9ed2-4f8ff1eb9d86,5539be2c-b9f5-471b-927c-c68c8fcb4db7,9bb77ac1-382b-46e3-a3d1-0c4e2ade8071 failed to submit, retrying in 15000 millis
```

### Suggestion

The bug could be in [Events.scala line 333](https://github.com/zalando-nakadi/kanadi/blob/master/src/main/scala/org/zalando/kanadi/api/Events.scala#L333
)
```scala
   
    val (notValid, retry) = errors.partition(
        response =>
            response.step
                .contains(Events.Step.Validating) || response.publishingStatus == Events.PublishingStatus.Submitted)
    val toRetry = events.filter { event =>
        eventWithUndefinedEventIdFallback(event) match {
            case Some(eid) => !retry.exists(_.eid.contains(eid))
            case None      => false
        }
```
the `partition` function will save successful events in the `notValid` variable and all failed events in the `retry` variable.
But then `toRetry` will contain all events that are not in the retry list `(!retry.exists(_.eid.contains(eid))`) --> the successful one

**Comment by mdedetrich** [comment] 2020-08-17 08:23
Thanks for the issue, I just made a bug report at https://github.com/zalando-nakadi/kanadi/pull/154, can you verify that it works?

In the meantime I am trying to make a test for this.

**Comment by mdedetrich** [comment] 2020-08-18 08:04
Closing this as the issue is resolved, if its a problem then please make a new ticket.

**Closed by mdedetrich** 2020-08-18 08:04 UTC
